package main

import (
	"errors"
	"fmt"
)

// 1. Define a global sentinel error
// Sentinel errors are useful for exact equality checks using errors.Is()
var ErrNegativeInput = errors.New("input cannot be a negative number")

// validateAge implements logical validation gates for age input
func validateAge(age int) error {
	// Gate 1: Check for negative input using a sentinel error
	if age < 0 {
		return ErrNegativeInput
	}

	// Gate 2: Check for unrealistic input using dynamic formatting
	if age > 150 {
		return fmt.Errorf("age %d is biologically impossible", age)
	}

	// Validation passed
	return nil
}

func RunCustomErrorsDemo() {
	// --- Scenario 1: Valid Input ---
	fmt.Println("--- SCENARIO 1: VALID INPUT ---")
	validAge := 25
	if err := validateAge(validAge); err == nil {
		fmt.Printf("[OK] Age %d is valid.\n", validAge)
	}
	fmt.Println()

	// --- Scenario 2: Sentinel Error Check ---
	fmt.Println("--- SCENARIO 2: SENTINEL ERROR ---")
	negativeAge := -5
	errSent := validateAge(negativeAge)
	if errSent != nil {
		// Use errors.Is to check if the error matches a specific sentinel
		if errors.Is(errSent, ErrNegativeInput) {
			fmt.Printf("[CATCH] Sentinel Match: %v\n", errSent)
		} else {
			fmt.Printf("[CATCH] Unexpected Error: %v\n", errSent)
		}
	}
	fmt.Println()

	// --- Scenario 3: Dynamic Error Check ---
	fmt.Println("--- SCENARIO 3: DYNAMIC FORMATTED ERROR ---")
	impossibleAge := 200
	errDyn := validateAge(impossibleAge)
	if errDyn != nil {
		// Printing the error message generated by fmt.Errorf
		fmt.Printf("[CATCH] Validation failed: %v\n", errDyn)
	}
}
